/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import { JSX } from '@stencil/core';


export namespace Components {
  interface ClickCounter {
    'max': any;
    'min': any;
    'startnumber': any;
    'step': any;
  }
  interface YourCounter {}
}

declare namespace LocalJSX {
  interface ClickCounter extends JSXBase.HTMLAttributes {
    'max'?: any;
    'min'?: any;
    'startnumber'?: any;
    'step'?: any;
  }
  interface YourCounter extends JSXBase.HTMLAttributes {}

  interface IntrinsicElements {
    'click-counter': ClickCounter;
    'your-counter': YourCounter;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


declare global {



  interface HTMLClickCounterElement extends Components.ClickCounter, HTMLStencilElement {}
  var HTMLClickCounterElement: {
    prototype: HTMLClickCounterElement;
    new (): HTMLClickCounterElement;
  };

  interface HTMLYourCounterElement extends Components.YourCounter, HTMLStencilElement {}
  var HTMLYourCounterElement: {
    prototype: HTMLYourCounterElement;
    new (): HTMLYourCounterElement;
  };

  interface HTMLElementTagNameMap {
    'click-counter': HTMLClickCounterElement;
    'your-counter': HTMLYourCounterElement;
  }

  interface ElementTagNameMap extends HTMLElementTagNameMap {}
}

